# Generated by Django 6.0.2 on 2026-02-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='blogs/')),
                ('author', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('external_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
