# Generated by Django 5.2.11 on 2026-02-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arusha_milk_ltd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='services/')),
                ('icon_class', models.CharField(help_text='Example: fa fa-truck', max_length=100)),
            ],
        ),
    ]
