# Generated by Django 5.2.11 on 2026-02-20 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arusha_milk_ltd', '0002_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
