# Generated by Django 6.0.2 on 2026-02-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arusha_milk_ltd', '0003_delete_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
